//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esEntity", Namespace="http://schemas.datacontract.org/2004/07/EntitySpaces.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.esSchedule))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Schedule))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.esScreenGroups))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.ScreenGroups))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.esTemplate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Template))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.esLoop))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Loop))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.esLoopContent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.LoopContent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.esContent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Content))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.esScreen))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Screen))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.esUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.User))]
    public partial class esEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ModifiedColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DisplayClient.ServiceReference1.esDataRowState RowStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] ModifiedColumns {
            get {
                return this.ModifiedColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedColumnsField, value) != true)) {
                    this.ModifiedColumnsField = value;
                    this.RaisePropertyChanged("ModifiedColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DisplayClient.ServiceReference1.esDataRowState RowState {
            get {
                return this.RowStateField;
            }
            set {
                if ((this.RowStateField.Equals(value) != true)) {
                    this.RowStateField = value;
                    this.RaisePropertyChanged("RowState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esSchedule", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Schedule))]
    public partial class esSchedule : DisplayClient.ServiceReference1.esEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> GroupidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LoopendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> LoopidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoopnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LoopstartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoopttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ScreenidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreennameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Createdby {
            get {
                return this.CreatedbyField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedbyField, value) != true)) {
                    this.CreatedbyField = value;
                    this.RaisePropertyChanged("Createdby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Createdon {
            get {
                return this.CreatedonField;
            }
            set {
                if ((this.CreatedonField.Equals(value) != true)) {
                    this.CreatedonField = value;
                    this.RaisePropertyChanged("Createdon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Groupid {
            get {
                return this.GroupidField;
            }
            set {
                if ((this.GroupidField.Equals(value) != true)) {
                    this.GroupidField = value;
                    this.RaisePropertyChanged("Groupid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Groupname {
            get {
                return this.GroupnameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupnameField, value) != true)) {
                    this.GroupnameField = value;
                    this.RaisePropertyChanged("Groupname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Loopend {
            get {
                return this.LoopendField;
            }
            set {
                if ((this.LoopendField.Equals(value) != true)) {
                    this.LoopendField = value;
                    this.RaisePropertyChanged("Loopend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Loopid {
            get {
                return this.LoopidField;
            }
            set {
                if ((this.LoopidField.Equals(value) != true)) {
                    this.LoopidField = value;
                    this.RaisePropertyChanged("Loopid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Loopname {
            get {
                return this.LoopnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoopnameField, value) != true)) {
                    this.LoopnameField = value;
                    this.RaisePropertyChanged("Loopname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Loopstart {
            get {
                return this.LoopstartField;
            }
            set {
                if ((this.LoopstartField.Equals(value) != true)) {
                    this.LoopstartField = value;
                    this.RaisePropertyChanged("Loopstart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Loopttype {
            get {
                return this.LoopttypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LoopttypeField, value) != true)) {
                    this.LoopttypeField = value;
                    this.RaisePropertyChanged("Loopttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Screenid {
            get {
                return this.ScreenidField;
            }
            set {
                if ((this.ScreenidField.Equals(value) != true)) {
                    this.ScreenidField = value;
                    this.RaisePropertyChanged("Screenid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Screenname {
            get {
                return this.ScreennameField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreennameField, value) != true)) {
                    this.ScreennameField = value;
                    this.RaisePropertyChanged("Screenname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Schedule : DisplayClient.ServiceReference1.esSchedule {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esScreenGroups", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.ScreenGroups))]
    public partial class esScreenGroups : DisplayClient.ServiceReference1.esEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScreenGroups", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class ScreenGroups : DisplayClient.ServiceReference1.esScreenGroups {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esTemplate", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Template))]
    public partial class esTemplate : DisplayClient.ServiceReference1.esEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OpacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonedescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonenameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> Opacity {
            get {
                return this.OpacityField;
            }
            set {
                if ((this.OpacityField.Equals(value) != true)) {
                    this.OpacityField = value;
                    this.RaisePropertyChanged("Opacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Zonedescription {
            get {
                return this.ZonedescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonedescriptionField, value) != true)) {
                    this.ZonedescriptionField = value;
                    this.RaisePropertyChanged("Zonedescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Zonename {
            get {
                return this.ZonenameField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonenameField, value) != true)) {
                    this.ZonenameField = value;
                    this.RaisePropertyChanged("Zonename");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Template", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Template : DisplayClient.ServiceReference1.esTemplate {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esLoop", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Loop))]
    public partial class esLoop : DisplayClient.ServiceReference1.esEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TemplateidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplatenameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Createdby {
            get {
                return this.CreatedbyField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedbyField, value) != true)) {
                    this.CreatedbyField = value;
                    this.RaisePropertyChanged("Createdby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Createdon {
            get {
                return this.CreatedonField;
            }
            set {
                if ((this.CreatedonField.Equals(value) != true)) {
                    this.CreatedonField = value;
                    this.RaisePropertyChanged("Createdon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Expiry {
            get {
                return this.ExpiryField;
            }
            set {
                if ((this.ExpiryField.Equals(value) != true)) {
                    this.ExpiryField = value;
                    this.RaisePropertyChanged("Expiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Templateid {
            get {
                return this.TemplateidField;
            }
            set {
                if ((this.TemplateidField.Equals(value) != true)) {
                    this.TemplateidField = value;
                    this.RaisePropertyChanged("Templateid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Templatename {
            get {
                return this.TemplatenameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplatenameField, value) != true)) {
                    this.TemplatenameField = value;
                    this.RaisePropertyChanged("Templatename");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loop", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Loop : DisplayClient.ServiceReference1.esLoop {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esLoopContent", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.LoopContent))]
    public partial class esLoopContent : DisplayClient.ServiceReference1.esEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> LoopidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoopnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> MediaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedianameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TemplateidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplatenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ZoneidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonenameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Loopid {
            get {
                return this.LoopidField;
            }
            set {
                if ((this.LoopidField.Equals(value) != true)) {
                    this.LoopidField = value;
                    this.RaisePropertyChanged("Loopid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Loopname {
            get {
                return this.LoopnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoopnameField, value) != true)) {
                    this.LoopnameField = value;
                    this.RaisePropertyChanged("Loopname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Mediaid {
            get {
                return this.MediaidField;
            }
            set {
                if ((this.MediaidField.Equals(value) != true)) {
                    this.MediaidField = value;
                    this.RaisePropertyChanged("Mediaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Medianame {
            get {
                return this.MedianameField;
            }
            set {
                if ((object.ReferenceEquals(this.MedianameField, value) != true)) {
                    this.MedianameField = value;
                    this.RaisePropertyChanged("Medianame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Templateid {
            get {
                return this.TemplateidField;
            }
            set {
                if ((this.TemplateidField.Equals(value) != true)) {
                    this.TemplateidField = value;
                    this.RaisePropertyChanged("Templateid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Templatename {
            get {
                return this.TemplatenameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplatenameField, value) != true)) {
                    this.TemplatenameField = value;
                    this.RaisePropertyChanged("Templatename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Zoneid {
            get {
                return this.ZoneidField;
            }
            set {
                if ((this.ZoneidField.Equals(value) != true)) {
                    this.ZoneidField = value;
                    this.RaisePropertyChanged("Zoneid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Zonename {
            get {
                return this.ZonenameField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonenameField, value) != true)) {
                    this.ZonenameField = value;
                    this.RaisePropertyChanged("Zonename");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoopContent", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class LoopContent : DisplayClient.ServiceReference1.esLoopContent {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esContent", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Content))]
    public partial class esContent : DisplayClient.ServiceReference1.esEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilelocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FilesizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ImportdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metadata9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SnapshotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UploadstatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Contenttype {
            get {
                return this.ContenttypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenttypeField, value) != true)) {
                    this.ContenttypeField = value;
                    this.RaisePropertyChanged("Contenttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Expiry {
            get {
                return this.ExpiryField;
            }
            set {
                if ((this.ExpiryField.Equals(value) != true)) {
                    this.ExpiryField = value;
                    this.RaisePropertyChanged("Expiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Filelocation {
            get {
                return this.FilelocationField;
            }
            set {
                if ((object.ReferenceEquals(this.FilelocationField, value) != true)) {
                    this.FilelocationField = value;
                    this.RaisePropertyChanged("Filelocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Filesize {
            get {
                return this.FilesizeField;
            }
            set {
                if ((this.FilesizeField.Equals(value) != true)) {
                    this.FilesizeField = value;
                    this.RaisePropertyChanged("Filesize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Importdate {
            get {
                return this.ImportdateField;
            }
            set {
                if ((this.ImportdateField.Equals(value) != true)) {
                    this.ImportdateField = value;
                    this.RaisePropertyChanged("Importdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata1 {
            get {
                return this.Metadata1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata1Field, value) != true)) {
                    this.Metadata1Field = value;
                    this.RaisePropertyChanged("Metadata1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata2 {
            get {
                return this.Metadata2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata2Field, value) != true)) {
                    this.Metadata2Field = value;
                    this.RaisePropertyChanged("Metadata2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata3 {
            get {
                return this.Metadata3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata3Field, value) != true)) {
                    this.Metadata3Field = value;
                    this.RaisePropertyChanged("Metadata3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata4 {
            get {
                return this.Metadata4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata4Field, value) != true)) {
                    this.Metadata4Field = value;
                    this.RaisePropertyChanged("Metadata4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata5 {
            get {
                return this.Metadata5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata5Field, value) != true)) {
                    this.Metadata5Field = value;
                    this.RaisePropertyChanged("Metadata5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata6 {
            get {
                return this.Metadata6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata6Field, value) != true)) {
                    this.Metadata6Field = value;
                    this.RaisePropertyChanged("Metadata6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata7 {
            get {
                return this.Metadata7Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata7Field, value) != true)) {
                    this.Metadata7Field = value;
                    this.RaisePropertyChanged("Metadata7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata8 {
            get {
                return this.Metadata8Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata8Field, value) != true)) {
                    this.Metadata8Field = value;
                    this.RaisePropertyChanged("Metadata8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metadata9 {
            get {
                return this.Metadata9Field;
            }
            set {
                if ((object.ReferenceEquals(this.Metadata9Field, value) != true)) {
                    this.Metadata9Field = value;
                    this.RaisePropertyChanged("Metadata9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Snapshot {
            get {
                return this.SnapshotField;
            }
            set {
                if ((object.ReferenceEquals(this.SnapshotField, value) != true)) {
                    this.SnapshotField = value;
                    this.RaisePropertyChanged("Snapshot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> Uploadstatus {
            get {
                return this.UploadstatusField;
            }
            set {
                if ((this.UploadstatusField.Equals(value) != true)) {
                    this.UploadstatusField = value;
                    this.RaisePropertyChanged("Uploadstatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Content", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Content : DisplayClient.ServiceReference1.esContent {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esScreen", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.Screen))]
    public partial class esScreen : DisplayClient.ServiceReference1.esEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastactiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreennameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Groupid {
            get {
                return this.GroupidField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupidField, value) != true)) {
                    this.GroupidField = value;
                    this.RaisePropertyChanged("Groupid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Lastactive {
            get {
                return this.LastactiveField;
            }
            set {
                if ((this.LastactiveField.Equals(value) != true)) {
                    this.LastactiveField = value;
                    this.RaisePropertyChanged("Lastactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Screenname {
            get {
                return this.ScreennameField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreennameField, value) != true)) {
                    this.ScreennameField = value;
                    this.RaisePropertyChanged("Screenname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Screen", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Screen : DisplayClient.ServiceReference1.esScreen {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="esUser", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DisplayClient.ServiceReference1.User))]
    public partial class esUser : DisplayClient.ServiceReference1.esEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastloginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Groupid {
            get {
                return this.GroupidField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupidField, value) != true)) {
                    this.GroupidField = value;
                    this.RaisePropertyChanged("Groupid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Lastlogin {
            get {
                return this.LastloginField;
            }
            set {
                if ((this.LastloginField.Equals(value) != true)) {
                    this.LastloginField = value;
                    this.RaisePropertyChanged("Lastlogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Loginid {
            get {
                return this.LoginidField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginidField, value) != true)) {
                    this.LoginidField = value;
                    this.RaisePropertyChanged("Loginid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class User : DisplayClient.ServiceReference1.esUser {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="esDataRowState", Namespace="www.entityspaces.net")]
    public enum esDataRowState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ScheduleCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Schedule")]
    [System.SerializableAttribute()]
    public class ScheduleCollection : System.Collections.Generic.List<DisplayClient.ServiceReference1.Schedule> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LoopContentCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="LoopContent")]
    [System.SerializableAttribute()]
    public class LoopContentCollection : System.Collections.Generic.List<DisplayClient.ServiceReference1.LoopContent> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TemplateCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Template")]
    [System.SerializableAttribute()]
    public class TemplateCollection : System.Collections.Generic.List<DisplayClient.ServiceReference1.Template> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LoopCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Loop")]
    [System.SerializableAttribute()]
    public class LoopCollection : System.Collections.Generic.List<DisplayClient.ServiceReference1.Loop> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ScreenGroupsCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="ScreenGroups")]
    [System.SerializableAttribute()]
    public class ScreenGroupsCollection : System.Collections.Generic.List<DisplayClient.ServiceReference1.ScreenGroups> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ScreenCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Screen")]
    [System.SerializableAttribute()]
    public class ScreenCollection : System.Collections.Generic.List<DisplayClient.ServiceReference1.Screen> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="User")]
    [System.SerializableAttribute()]
    public class UserCollection : System.Collections.Generic.List<DisplayClient.ServiceReference1.User> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CoreService")]
    public interface CoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectDelta", ReplyAction="http://tempuri.org/CoreService/CollectDeltaResponse")]
        long CollectDelta(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/VerifyLogin", ReplyAction="http://tempuri.org/CoreService/VerifyLoginResponse")]
        DisplayClient.ServiceReference1.User VerifyLogin(string login, string passwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/UpdateScheduleForScreens", ReplyAction="http://tempuri.org/CoreService/UpdateScheduleForScreensResponse")]
        bool UpdateScheduleForScreens(DisplayClient.ServiceReference1.ScheduleCollection scheduleCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/UpdateScheduleForGroups", ReplyAction="http://tempuri.org/CoreService/UpdateScheduleForGroupsResponse")]
        bool UpdateScheduleForGroups(DisplayClient.ServiceReference1.ScheduleCollection scheduleCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectScheduleForScreen", ReplyAction="http://tempuri.org/CoreService/CollectScheduleForScreenResponse")]
        DisplayClient.ServiceReference1.ScheduleCollection CollectScheduleForScreen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectScheduleForScreenGroup", ReplyAction="http://tempuri.org/CoreService/CollectScheduleForScreenGroupResponse")]
        DisplayClient.ServiceReference1.ScheduleCollection CollectScheduleForScreenGroup(DisplayClient.ServiceReference1.ScreenGroups group, System.DateTime datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectLoopContentForZone", ReplyAction="http://tempuri.org/CoreService/CollectLoopContentForZoneResponse")]
        DisplayClient.ServiceReference1.LoopContentCollection CollectLoopContentForZone(DisplayClient.ServiceReference1.Template zone, DisplayClient.ServiceReference1.Loop loop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectLoopContentForZoneByName", ReplyAction="http://tempuri.org/CoreService/CollectLoopContentForZoneByNameResponse")]
        DisplayClient.ServiceReference1.LoopContentCollection CollectLoopContentForZoneByName(string zonename, string loopname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/ApplyLoopContentCollection", ReplyAction="http://tempuri.org/CoreService/ApplyLoopContentCollectionResponse")]
        bool ApplyLoopContentCollection(DisplayClient.ServiceReference1.LoopContentCollection contentForZone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/TESTInsertGroup", ReplyAction="http://tempuri.org/CoreService/TESTInsertGroupResponse")]
        bool TESTInsertGroup(DisplayClient.ServiceReference1.ScreenGroups s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectSCreenGroup", ReplyAction="http://tempuri.org/CoreService/CollectSCreenGroupResponse")]
        DisplayClient.ServiceReference1.ScreenGroups CollectSCreenGroup(DisplayClient.ServiceReference1.ScreenGroups s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectLoopContentCollection", ReplyAction="http://tempuri.org/CoreService/CollectLoopContentCollectionResponse")]
        DisplayClient.ServiceReference1.LoopContentCollection CollectLoopContentCollection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectTemplates", ReplyAction="http://tempuri.org/CoreService/CollectTemplatesResponse")]
        DisplayClient.ServiceReference1.TemplateCollection CollectTemplates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectZonesForTemplate", ReplyAction="http://tempuri.org/CoreService/CollectZonesForTemplateResponse")]
        DisplayClient.ServiceReference1.TemplateCollection CollectZonesForTemplate(DisplayClient.ServiceReference1.Template zone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectZonesForThisTemplateName", ReplyAction="http://tempuri.org/CoreService/CollectZonesForThisTemplateNameResponse")]
        DisplayClient.ServiceReference1.TemplateCollection CollectZonesForThisTemplateName(string templateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/ChangeMedia", ReplyAction="http://tempuri.org/CoreService/ChangeMediaResponse")]
        long ChangeMedia(DisplayClient.ServiceReference1.Content mediaName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/InsertScheduleItem", ReplyAction="http://tempuri.org/CoreService/InsertScheduleItemResponse")]
        bool InsertScheduleItem(DisplayClient.ServiceReference1.Schedule schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/InsertMedia", ReplyAction="http://tempuri.org/CoreService/InsertMediaResponse")]
        long InsertMedia(DisplayClient.ServiceReference1.Content media);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/InsertTemplate", ReplyAction="http://tempuri.org/CoreService/InsertTemplateResponse")]
        bool InsertTemplate(DisplayClient.ServiceReference1.Template template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/RemoveTemplate", ReplyAction="http://tempuri.org/CoreService/RemoveTemplateResponse")]
        bool RemoveTemplate(DisplayClient.ServiceReference1.Template templateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/UpdateScheduleItem", ReplyAction="http://tempuri.org/CoreService/UpdateScheduleItemResponse")]
        bool UpdateScheduleItem(DisplayClient.ServiceReference1.Schedule schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/ChangeTemplate", ReplyAction="http://tempuri.org/CoreService/ChangeTemplateResponse")]
        bool ChangeTemplate(DisplayClient.ServiceReference1.Template templateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectMedia", ReplyAction="http://tempuri.org/CoreService/CollectMediaResponse")]
        DisplayClient.ServiceReference1.Content[] CollectMedia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectLoops", ReplyAction="http://tempuri.org/CoreService/CollectLoopsResponse")]
        DisplayClient.ServiceReference1.LoopCollection CollectLoops();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectThisLoop", ReplyAction="http://tempuri.org/CoreService/CollectThisLoopResponse")]
        DisplayClient.ServiceReference1.Loop CollectThisLoop(string loopName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/InsertLoop", ReplyAction="http://tempuri.org/CoreService/InsertLoopResponse")]
        bool InsertLoop(DisplayClient.ServiceReference1.Loop loop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/RemoveLoop", ReplyAction="http://tempuri.org/CoreService/RemoveLoopResponse")]
        bool RemoveLoop(DisplayClient.ServiceReference1.Loop loop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectScreenGroups", ReplyAction="http://tempuri.org/CoreService/CollectScreenGroupsResponse")]
        DisplayClient.ServiceReference1.ScreenGroupsCollection CollectScreenGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectScreens", ReplyAction="http://tempuri.org/CoreService/CollectScreensResponse")]
        DisplayClient.ServiceReference1.ScreenCollection CollectScreens();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/RegisterDisplayClientLogin", ReplyAction="http://tempuri.org/CoreService/RegisterDisplayClientLoginResponse")]
        string RegisterDisplayClientLogin(string screenid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/InsertScreen", ReplyAction="http://tempuri.org/CoreService/InsertScreenResponse")]
        bool InsertScreen(DisplayClient.ServiceReference1.Screen screen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/CollectUsers", ReplyAction="http://tempuri.org/CoreService/CollectUsersResponse")]
        DisplayClient.ServiceReference1.UserCollection CollectUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/RemoveUser", ReplyAction="http://tempuri.org/CoreService/RemoveUserResponse")]
        bool RemoveUser(DisplayClient.ServiceReference1.User userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/RemoveMedia", ReplyAction="http://tempuri.org/CoreService/RemoveMediaResponse")]
        bool RemoveMedia(DisplayClient.ServiceReference1.Content _content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/RemoveTicker", ReplyAction="http://tempuri.org/CoreService/RemoveTickerResponse")]
        bool RemoveTicker(DisplayClient.ServiceReference1.Content _content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/InsertOrUpdateTicker", ReplyAction="http://tempuri.org/CoreService/InsertOrUpdateTickerResponse")]
        bool InsertOrUpdateTicker(DisplayClient.ServiceReference1.Content ticker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/InsertUser", ReplyAction="http://tempuri.org/CoreService/InsertUserResponse")]
        bool InsertUser(DisplayClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/ChangeUser", ReplyAction="http://tempuri.org/CoreService/ChangeUserResponse")]
        bool ChangeUser(DisplayClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/RemoveGroup", ReplyAction="http://tempuri.org/CoreService/RemoveGroupResponse")]
        bool RemoveGroup(DisplayClient.ServiceReference1.ScreenGroups groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/ChangeScreenGroup", ReplyAction="http://tempuri.org/CoreService/ChangeScreenGroupResponse")]
        bool ChangeScreenGroup(DisplayClient.ServiceReference1.Screen screen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/RemoveScreen", ReplyAction="http://tempuri.org/CoreService/RemoveScreenResponse")]
        bool RemoveScreen(DisplayClient.ServiceReference1.Screen screenName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoreService/InsertScreenGroup", ReplyAction="http://tempuri.org/CoreService/InsertScreenGroupResponse")]
        bool InsertScreenGroup(DisplayClient.ServiceReference1.ScreenGroups scrg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoreServiceChannel : DisplayClient.ServiceReference1.CoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreServiceClient : System.ServiceModel.ClientBase<DisplayClient.ServiceReference1.CoreService>, DisplayClient.ServiceReference1.CoreService {
        
        public CoreServiceClient() {
        }
        
        public CoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long CollectDelta(string name) {
            return base.Channel.CollectDelta(name);
        }
        
        public DisplayClient.ServiceReference1.User VerifyLogin(string login, string passwd) {
            return base.Channel.VerifyLogin(login, passwd);
        }
        
        public bool UpdateScheduleForScreens(DisplayClient.ServiceReference1.ScheduleCollection scheduleCollection) {
            return base.Channel.UpdateScheduleForScreens(scheduleCollection);
        }
        
        public bool UpdateScheduleForGroups(DisplayClient.ServiceReference1.ScheduleCollection scheduleCollection) {
            return base.Channel.UpdateScheduleForGroups(scheduleCollection);
        }
        
        public DisplayClient.ServiceReference1.ScheduleCollection CollectScheduleForScreen() {
            return base.Channel.CollectScheduleForScreen();
        }
        
        public DisplayClient.ServiceReference1.ScheduleCollection CollectScheduleForScreenGroup(DisplayClient.ServiceReference1.ScreenGroups group, System.DateTime datetime) {
            return base.Channel.CollectScheduleForScreenGroup(group, datetime);
        }
        
        public DisplayClient.ServiceReference1.LoopContentCollection CollectLoopContentForZone(DisplayClient.ServiceReference1.Template zone, DisplayClient.ServiceReference1.Loop loop) {
            return base.Channel.CollectLoopContentForZone(zone, loop);
        }
        
        public DisplayClient.ServiceReference1.LoopContentCollection CollectLoopContentForZoneByName(string zonename, string loopname) {
            return base.Channel.CollectLoopContentForZoneByName(zonename, loopname);
        }
        
        public bool ApplyLoopContentCollection(DisplayClient.ServiceReference1.LoopContentCollection contentForZone) {
            return base.Channel.ApplyLoopContentCollection(contentForZone);
        }
        
        public bool TESTInsertGroup(DisplayClient.ServiceReference1.ScreenGroups s) {
            return base.Channel.TESTInsertGroup(s);
        }
        
        public DisplayClient.ServiceReference1.ScreenGroups CollectSCreenGroup(DisplayClient.ServiceReference1.ScreenGroups s) {
            return base.Channel.CollectSCreenGroup(s);
        }
        
        public DisplayClient.ServiceReference1.LoopContentCollection CollectLoopContentCollection() {
            return base.Channel.CollectLoopContentCollection();
        }
        
        public DisplayClient.ServiceReference1.TemplateCollection CollectTemplates() {
            return base.Channel.CollectTemplates();
        }
        
        public DisplayClient.ServiceReference1.TemplateCollection CollectZonesForTemplate(DisplayClient.ServiceReference1.Template zone) {
            return base.Channel.CollectZonesForTemplate(zone);
        }
        
        public DisplayClient.ServiceReference1.TemplateCollection CollectZonesForThisTemplateName(string templateName) {
            return base.Channel.CollectZonesForThisTemplateName(templateName);
        }
        
        public long ChangeMedia(DisplayClient.ServiceReference1.Content mediaName) {
            return base.Channel.ChangeMedia(mediaName);
        }
        
        public bool InsertScheduleItem(DisplayClient.ServiceReference1.Schedule schedule) {
            return base.Channel.InsertScheduleItem(schedule);
        }
        
        public long InsertMedia(DisplayClient.ServiceReference1.Content media) {
            return base.Channel.InsertMedia(media);
        }
        
        public bool InsertTemplate(DisplayClient.ServiceReference1.Template template) {
            return base.Channel.InsertTemplate(template);
        }
        
        public bool RemoveTemplate(DisplayClient.ServiceReference1.Template templateName) {
            return base.Channel.RemoveTemplate(templateName);
        }
        
        public bool UpdateScheduleItem(DisplayClient.ServiceReference1.Schedule schedule) {
            return base.Channel.UpdateScheduleItem(schedule);
        }
        
        public bool ChangeTemplate(DisplayClient.ServiceReference1.Template templateName) {
            return base.Channel.ChangeTemplate(templateName);
        }
        
        public DisplayClient.ServiceReference1.Content[] CollectMedia() {
            return base.Channel.CollectMedia();
        }
        
        public DisplayClient.ServiceReference1.LoopCollection CollectLoops() {
            return base.Channel.CollectLoops();
        }
        
        public DisplayClient.ServiceReference1.Loop CollectThisLoop(string loopName) {
            return base.Channel.CollectThisLoop(loopName);
        }
        
        public bool InsertLoop(DisplayClient.ServiceReference1.Loop loop) {
            return base.Channel.InsertLoop(loop);
        }
        
        public bool RemoveLoop(DisplayClient.ServiceReference1.Loop loop) {
            return base.Channel.RemoveLoop(loop);
        }
        
        public DisplayClient.ServiceReference1.ScreenGroupsCollection CollectScreenGroups() {
            return base.Channel.CollectScreenGroups();
        }
        
        public DisplayClient.ServiceReference1.ScreenCollection CollectScreens() {
            return base.Channel.CollectScreens();
        }
        
        public string RegisterDisplayClientLogin(string screenid) {
            return base.Channel.RegisterDisplayClientLogin(screenid);
        }
        
        public bool InsertScreen(DisplayClient.ServiceReference1.Screen screen) {
            return base.Channel.InsertScreen(screen);
        }
        
        public DisplayClient.ServiceReference1.UserCollection CollectUsers() {
            return base.Channel.CollectUsers();
        }
        
        public bool RemoveUser(DisplayClient.ServiceReference1.User userName) {
            return base.Channel.RemoveUser(userName);
        }
        
        public bool RemoveMedia(DisplayClient.ServiceReference1.Content _content) {
            return base.Channel.RemoveMedia(_content);
        }
        
        public bool RemoveTicker(DisplayClient.ServiceReference1.Content _content) {
            return base.Channel.RemoveTicker(_content);
        }
        
        public bool InsertOrUpdateTicker(DisplayClient.ServiceReference1.Content ticker) {
            return base.Channel.InsertOrUpdateTicker(ticker);
        }
        
        public bool InsertUser(DisplayClient.ServiceReference1.User user) {
            return base.Channel.InsertUser(user);
        }
        
        public bool ChangeUser(DisplayClient.ServiceReference1.User user) {
            return base.Channel.ChangeUser(user);
        }
        
        public bool RemoveGroup(DisplayClient.ServiceReference1.ScreenGroups groupName) {
            return base.Channel.RemoveGroup(groupName);
        }
        
        public bool ChangeScreenGroup(DisplayClient.ServiceReference1.Screen screen) {
            return base.Channel.ChangeScreenGroup(screen);
        }
        
        public bool RemoveScreen(DisplayClient.ServiceReference1.Screen screenName) {
            return base.Channel.RemoveScreen(screenName);
        }
        
        public bool InsertScreenGroup(DisplayClient.ServiceReference1.ScreenGroups scrg) {
            return base.Channel.InsertScreenGroup(scrg);
        }
    }
}
